// Feriados que ya habíamos cargado en el prototipo HTML — se pueden importar de una
// desde Incidencias, en vez de cargarlos uno por uno a mano.
export const FERIADOS_DEFAULT = [
  { fecha: '2026-06-05', motivo: 'Día mundial del medio ambiente', bloquea: false },
  { fecha: '2026-07-09', motivo: 'Día de la Independencia', bloquea: true },
  { fecha: '2026-07-30', motivo: 'Día mundial contra la trata', bloquea: false },
  { fecha: '2026-10-05', motivo: 'Día mundial de los docentes', bloquea: false },
  { fecha: '2026-10-12', motivo: 'Día del Respeto a la Diversidad Cultural', bloquea: false },
  { fecha: '2026-10-22', motivo: 'Rosh hashana (Año nuevo judío)', bloquea: false },
  { fecha: '2026-12-08', motivo: 'Día de la Virgen', bloquea: true },
  { fecha: '2026-12-24', motivo: 'Noche buena', bloquea: true },
  { fecha: '2026-12-25', motivo: 'Navidad', bloquea: true },
  { fecha: '2026-12-31', motivo: 'Fin de año', bloquea: true },
  { fecha: '2027-01-01', motivo: 'Año nuevo', bloquea: true },
  { fecha: '2027-01-27', motivo: 'Día internacional de conmemoración anual en memoria de las víctimas', bloquea: true },
  { fecha: '2027-02-03', motivo: 'Día internacional de la educación', bloquea: false },
  { fecha: '2027-02-08', motivo: 'Carnaval', bloquea: true },
  { fecha: '2027-02-09', motivo: 'Carnaval', bloquea: true },
  { fecha: '2027-03-08', motivo: 'Día internacional de la mujer', bloquea: false },
  { fecha: '2027-03-24', motivo: 'Día Nacional de la Memoria por la Verdad y la Justicia', bloquea: true },
  { fecha: '2027-03-25', motivo: 'Jueves Santo', bloquea: true },
  { fecha: '2027-03-26', motivo: 'Viernes Santo', bloquea: true },
  { fecha: '2027-04-02', motivo: 'Día del Veterano y de los Caídos en la Guerra de Malvinas', bloquea: true },
  { fecha: '2027-04-06', motivo: 'Día del coach', bloquea: false },
  { fecha: '2027-05-01', motivo: 'Día Internacional de los Trabajadores', bloquea: true },
  { fecha: '2026-05-12', motivo: 'Semana internacional del coaching', bloquea: false },
  { fecha: '2026-05-13', motivo: 'Semana internacional del coaching', bloquea: false },
  { fecha: '2026-05-14', motivo: 'Semana internacional del coaching', bloquea: false },
  { fecha: '2026-05-15', motivo: 'Semana internacional del coaching', bloquea: false },
  { fecha: '2026-05-16', motivo: 'Semana internacional del coaching', bloquea: false },
  { fecha: '2026-05-17', motivo: 'Semana internacional del coaching', bloquea: false },
  { fecha: '2026-05-18', motivo: 'Semana internacional del coaching', bloquea: false },
  { fecha: '2027-05-25', motivo: 'Día de la Revolución de Mayo', bloquea: true },
  { fecha: '2027-06-21', motivo: 'Paso a la Inmortalidad del General Martín Güemes', bloquea: true },
  { fecha: '2027-07-09', motivo: 'Día de la Independencia', bloquea: true },
  { fecha: '2027-08-16', motivo: 'Paso a la Inmortalidad del Gral. José de San Martín', bloquea: true },
  { fecha: '2027-10-11', motivo: 'Día del Respeto a la Diversidad Cultural', bloquea: true }
];
