// Leyenda de los íconos de trazo uniforme (fuente /public/fonts/iconos.woff2, Lucide, licencia ISC).
// En el código aparecen como un carácter invisible del rango privado (se ve como un cuadradito en el editor).
// Este archivo solo documenta cuál es cuál; no se importa desde ningún lado.
export const ICONOS_LEYENDA = {
  '\ue03a': 'alarm-clock',
  '\ue04c': 'arrow-left',
  '\ue069': 'calendar',
  '\ue06d': 'check',
  '\ue087': 'clipboard-list',
  '\ue088': 'clock',
  '\ue0b3': 'download',
  '\ue0bb': 'eye',
  '\ue0e8': 'globe',
  '\ue0fb': 'info',
  '\ue103': 'library',
  '\ue105': 'link',
  '\ue10c': 'lock',
  '\ue110': 'mail',
  '\ue11f': 'moon',
  '\ue13f': 'plus',
  '\ue148': 'repeat',
  '\ue153': 'search',
  '\ue165': 'smartphone',
  '\ue174': 'square-pen',
  '\ue178': 'star',
  '\ue17a': 'sun',
  '\ue18c': 'trash-2',
  '\ue18f': 'trending-up',
  '\ue191': 'triangle-alert',
  '\ue19d': 'user',
  '\ue1b0': 'x',
  '\ue1f7': 'pencil',
  '\ue233': 'graduation-cap',
  '\ue295': 'hourglass',
  '\ue2a1': 'bar-chart-3',
  '\ue2b8': 'calendar-days',
  '\ue2f0': 'stethoscope',
  '\ue3e6': 'school',
  '\ue416': 'sparkles',
  '\ue4a7': 'key-round',
  '\ue4a9': 'goal',
};
